using LiftLog.Backend.Core.Entities;
using LiftLog.Backend.Core.Shared;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

namespace LiftLog.Backend.Infrastructure.Seeds;

public class ExerciseSeeder
{
    private static readonly (string Name, string[] MuscleGroups)[] Exercises =
    [
        (
            ExerciseNameConstants.AirSquat,
            [
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Calves,
            ]
        ),
        (
            ExerciseNameConstants.ArnoldPress,
            [MuscleGroupsNameConstants.Shoulders, MuscleGroupsNameConstants.Triceps]
        ),
        (
            ExerciseNameConstants.AssistedChinUp,
            [
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Biceps,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (
            ExerciseNameConstants.AssistedDip,
            [
                MuscleGroupsNameConstants.Chest,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Triceps,
            ]
        ),
        (
            ExerciseNameConstants.AssistedPullUp,
            [
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Biceps,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (
            ExerciseNameConstants.BackExtension,
            [
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Hamstrings,
            ]
        ),
        (
            ExerciseNameConstants.BallSlams,
            [
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Core,
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Shoulders,
            ]
        ),
        (
            ExerciseNameConstants.BarbellCurl,
            [MuscleGroupsNameConstants.Biceps, MuscleGroupsNameConstants.Forearms]
        ),
        (ExerciseNameConstants.BarbellFrontRaise, [MuscleGroupsNameConstants.Shoulders]),
        (
            ExerciseNameConstants.BarbellHackSquat,
            [
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Forearms,
                MuscleGroupsNameConstants.Calves,
            ]
        ),
        (ExerciseNameConstants.BarbellInclineTricepsExtension, [MuscleGroupsNameConstants.Triceps]),
        (
            ExerciseNameConstants.BarbellLunge,
            [MuscleGroupsNameConstants.Quads, MuscleGroupsNameConstants.Glutes]
        ),
        (ExerciseNameConstants.BarbellLyingTricepsExtension, [MuscleGroupsNameConstants.Triceps]),
        (
            ExerciseNameConstants.BarbellPreacherCurl,
            [MuscleGroupsNameConstants.Biceps, MuscleGroupsNameConstants.Forearms]
        ),
        (
            ExerciseNameConstants.BarbellRearDeltRow,
            [
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Biceps,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (
            ExerciseNameConstants.BarbellRow,
            [
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Biceps,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (ExerciseNameConstants.BarbellSeatedCalfRaise, [MuscleGroupsNameConstants.Calves]),
        (
            ExerciseNameConstants.BarbellShrug,
            [MuscleGroupsNameConstants.Traps, MuscleGroupsNameConstants.Forearms]
        ),
        (ExerciseNameConstants.BarbellStandingCalfRaise, [MuscleGroupsNameConstants.Calves]),
        (
            ExerciseNameConstants.BarbellStandingTricepsExtension,
            [MuscleGroupsNameConstants.Triceps]
        ),
        (
            ExerciseNameConstants.BarbellUprightRow,
            [
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Biceps,
            ]
        ),
        (
            ExerciseNameConstants.BarbellWalkingLunge,
            [MuscleGroupsNameConstants.Quads, MuscleGroupsNameConstants.Glutes]
        ),
        (ExerciseNameConstants.BarbellWristCurl, [MuscleGroupsNameConstants.Forearms]),
        (ExerciseNameConstants.BarbellWristCurlBehindTheBack, [MuscleGroupsNameConstants.Forearms]),
        (ExerciseNameConstants.BarbellWristExtension, [MuscleGroupsNameConstants.Forearms]),
        (
            ExerciseNameConstants.BarDip,
            [
                MuscleGroupsNameConstants.Chest,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Triceps,
            ]
        ),
        (ExerciseNameConstants.BarHang, [MuscleGroupsNameConstants.Forearms]),
        (
            ExerciseNameConstants.BayesianCurl,
            [MuscleGroupsNameConstants.Biceps, MuscleGroupsNameConstants.Forearms]
        ),
        (
            ExerciseNameConstants.BenchDip,
            [
                MuscleGroupsNameConstants.Triceps,
                MuscleGroupsNameConstants.Chest,
                MuscleGroupsNameConstants.Shoulders,
            ]
        ),
        (
            ExerciseNameConstants.BenchPress,
            [
                MuscleGroupsNameConstants.Chest,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Triceps,
            ]
        ),
        (
            ExerciseNameConstants.BeltSquat,
            [
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Calves,
            ]
        ),
        (ExerciseNameConstants.BicycleCrunch, [MuscleGroupsNameConstants.Core]),
        (
            ExerciseNameConstants.BlockClean,
            [
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Hamstrings,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Forearms,
                MuscleGroupsNameConstants.Calves,
            ]
        ),
        (
            ExerciseNameConstants.BlockSnatch,
            [
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Hamstrings,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Forearms,
                MuscleGroupsNameConstants.Calves,
            ]
        ),
        (
            ExerciseNameConstants.BoardPress,
            [
                MuscleGroupsNameConstants.Chest,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Triceps,
            ]
        ),
        (
            ExerciseNameConstants.BodyweightCurl,
            [
                MuscleGroupsNameConstants.Biceps,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (
            ExerciseNameConstants.BodyWeightLunge,
            [MuscleGroupsNameConstants.Quads, MuscleGroupsNameConstants.Glutes]
        ),
        (
            ExerciseNameConstants.BodyweightLegCurl,
            [MuscleGroupsNameConstants.Hamstrings, MuscleGroupsNameConstants.Glutes]
        ),
        (
            ExerciseNameConstants.BoxJump,
            [
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Calves,
            ]
        ),
        (
            ExerciseNameConstants.BoxSquat,
            [
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Calves,
            ]
        ),
        (
            ExerciseNameConstants.BulgarianSplitSquat,
            [
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Glutes,
            ]
        ),
        (
            ExerciseNameConstants.CableCloseGripSeatedRow,
            [
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Biceps,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (
            ExerciseNameConstants.CableCrossoverBicepCurl,
            [MuscleGroupsNameConstants.Biceps, MuscleGroupsNameConstants.Forearms]
        ),
        (ExerciseNameConstants.CableCrunch, [MuscleGroupsNameConstants.Core]),
        (
            ExerciseNameConstants.CableCurlWithBar,
            [MuscleGroupsNameConstants.Biceps, MuscleGroupsNameConstants.Forearms]
        ),
        (
            ExerciseNameConstants.CableCurlWithRope,
            [MuscleGroupsNameConstants.Biceps, MuscleGroupsNameConstants.Forearms]
        ),
        (ExerciseNameConstants.CableFrontRaise, [MuscleGroupsNameConstants.Shoulders]),
        (
            ExerciseNameConstants.CableGluteKickback,
            [MuscleGroupsNameConstants.Glutes, MuscleGroupsNameConstants.Hamstrings]
        ),
        (ExerciseNameConstants.CableLateralRaise, [MuscleGroupsNameConstants.Shoulders]),
        (ExerciseNameConstants.CableMachineHipAbduction, [MuscleGroupsNameConstants.Glutes]),
        (ExerciseNameConstants.CableMachineHipAdduction, [MuscleGroupsNameConstants.Adductors]),
        (
            ExerciseNameConstants.CableRearDeltRow,
            [
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Biceps,
            ]
        ),
        (
            ExerciseNameConstants.CableWideGripSeatedRow,
            [
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Biceps,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (
            ExerciseNameConstants.CableChestPress,
            [
                MuscleGroupsNameConstants.Chest,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Triceps,
            ]
        ),
        (
            ExerciseNameConstants.CablePullThrough,
            [
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Hamstrings,
                MuscleGroupsNameConstants.Back,
            ]
        ),
        (
            ExerciseNameConstants.ChairSquat,
            [
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Calves,
            ]
        ),
        (
            ExerciseNameConstants.ChestToBar,
            [
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Biceps,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (
            ExerciseNameConstants.ChinUp,
            [
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Biceps,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (
            ExerciseNameConstants.Clean,
            [
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Hamstrings,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Forearms,
                MuscleGroupsNameConstants.Calves,
            ]
        ),
        (
            ExerciseNameConstants.CleanAndJerk,
            [
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Hamstrings,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Forearms,
                MuscleGroupsNameConstants.Calves,
            ]
        ),
        (
            ExerciseNameConstants.ClapPushUp,
            [
                MuscleGroupsNameConstants.Chest,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Triceps,
            ]
        ),
        (ExerciseNameConstants.Clamshells, [MuscleGroupsNameConstants.Glutes]),
        (
            ExerciseNameConstants.CloseGripBenchPress,
            [
                MuscleGroupsNameConstants.Triceps,
                MuscleGroupsNameConstants.Chest,
                MuscleGroupsNameConstants.Shoulders,
            ]
        ),
        (
            ExerciseNameConstants.CloseGripChinUp,
            [
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Biceps,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (
            ExerciseNameConstants.CloseGripFeetUpBenchPress,
            [
                MuscleGroupsNameConstants.Triceps,
                MuscleGroupsNameConstants.Chest,
                MuscleGroupsNameConstants.Shoulders,
            ]
        ),
        (
            ExerciseNameConstants.CloseGripLatPulldown,
            [
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Biceps,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (
            ExerciseNameConstants.CloseGripPushUp,
            [
                MuscleGroupsNameConstants.Triceps,
                MuscleGroupsNameConstants.Core,
                MuscleGroupsNameConstants.Chest,
                MuscleGroupsNameConstants.Shoulders,
            ]
        ),
        (
            ExerciseNameConstants.CobraPushUp,
            [
                MuscleGroupsNameConstants.Chest,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Triceps,
                MuscleGroupsNameConstants.Core,
            ]
        ),
        (
            ExerciseNameConstants.ConcentrationCurl,
            [MuscleGroupsNameConstants.Biceps, MuscleGroupsNameConstants.Forearms]
        ),
        (ExerciseNameConstants.CopenhagenPlank, [MuscleGroupsNameConstants.Core]),
        (ExerciseNameConstants.CoreTwist, [MuscleGroupsNameConstants.Core]),
        (
            ExerciseNameConstants.CossackSquat,
            [
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Hamstrings,
            ]
        ),
        (ExerciseNameConstants.CrossbodyCableTricepsExtension, [MuscleGroupsNameConstants.Triceps]),
        (ExerciseNameConstants.Crunch, [MuscleGroupsNameConstants.Core]),
        (
            ExerciseNameConstants.CubanPress,
            [
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Triceps,
            ]
        ),
        (
            ExerciseNameConstants.CurtsyLunge,
            [MuscleGroupsNameConstants.Quads, MuscleGroupsNameConstants.Glutes]
        ),
        (ExerciseNameConstants.DeadBug, [MuscleGroupsNameConstants.Core]),
        (ExerciseNameConstants.DeadBugWithDumbbells, [MuscleGroupsNameConstants.Core]),
        (
            ExerciseNameConstants.Deadlift,
            [
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Hamstrings,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (
            ExerciseNameConstants.DeathMarchWithDumbbells,
            [
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Hamstrings,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Forearms,
                MuscleGroupsNameConstants.Traps,
            ]
        ),
        (
            ExerciseNameConstants.DeclineBenchPress,
            [
                MuscleGroupsNameConstants.Chest,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Triceps,
            ]
        ),
        (
            ExerciseNameConstants.DeclinePushUp,
            [
                MuscleGroupsNameConstants.Chest,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Triceps,
                MuscleGroupsNameConstants.Core,
            ]
        ),
        (
            ExerciseNameConstants.DeficitDeadlift,
            [
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Hamstrings,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (
            ExerciseNameConstants.DevilsPress,
            [
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Chest,
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Forearms,
                MuscleGroupsNameConstants.Calves,
                MuscleGroupsNameConstants.Core,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Triceps,
            ]
        ),
        (ExerciseNameConstants.DonkeyCalfRaise, [MuscleGroupsNameConstants.Calves]),
        (
            ExerciseNameConstants.DonkeyKicks,
            [MuscleGroupsNameConstants.Glutes, MuscleGroupsNameConstants.Hamstrings]
        ),
        (
            ExerciseNameConstants.DragCurl,
            [MuscleGroupsNameConstants.Biceps, MuscleGroupsNameConstants.Forearms]
        ),
        (
            ExerciseNameConstants.DragonFlag,
            [MuscleGroupsNameConstants.Core, MuscleGroupsNameConstants.Back]
        ),
        (
            ExerciseNameConstants.DumbbellChestFly,
            [MuscleGroupsNameConstants.Chest, MuscleGroupsNameConstants.Shoulders]
        ),
        (
            ExerciseNameConstants.DumbbellChestPress,
            [
                MuscleGroupsNameConstants.Chest,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Triceps,
            ]
        ),
        (
            ExerciseNameConstants.DumbbellCurl,
            [MuscleGroupsNameConstants.Biceps, MuscleGroupsNameConstants.Forearms]
        ),
        (
            ExerciseNameConstants.DumbbellDeadlift,
            [
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Hamstrings,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (
            ExerciseNameConstants.DumbbellDeclineChestPress,
            [
                MuscleGroupsNameConstants.Chest,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Triceps,
            ]
        ),
        (
            ExerciseNameConstants.DumbbellFloorPress,
            [
                MuscleGroupsNameConstants.Chest,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Triceps,
            ]
        ),
        (ExerciseNameConstants.DumbbellFrontRaise, [MuscleGroupsNameConstants.Shoulders]),
        (
            ExerciseNameConstants.DumbbellFrogPumps,
            [MuscleGroupsNameConstants.Glutes, MuscleGroupsNameConstants.Hamstrings]
        ),
        (ExerciseNameConstants.DumbbellLateralRaise, [MuscleGroupsNameConstants.Shoulders]),
        (
            ExerciseNameConstants.DumbbellLunge,
            [
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (ExerciseNameConstants.DumbbellLyingTricepsExtension, [MuscleGroupsNameConstants.Triceps]),
        (
            ExerciseNameConstants.DumbbellPreacherCurl,
            [MuscleGroupsNameConstants.Biceps, MuscleGroupsNameConstants.Forearms]
        ),
        (
            ExerciseNameConstants.DumbbellPullover,
            [MuscleGroupsNameConstants.Chest, MuscleGroupsNameConstants.Back]
        ),
        (
            ExerciseNameConstants.DumbbellRearDeltRow,
            [
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Biceps,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (
            ExerciseNameConstants.DumbbellRomanianDeadlift,
            [
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Hamstrings,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (
            ExerciseNameConstants.DumbbellRow,
            [
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (
            ExerciseNameConstants.DumbbellShoulderPress,
            [MuscleGroupsNameConstants.Shoulders, MuscleGroupsNameConstants.Triceps]
        ),
        (
            ExerciseNameConstants.DumbbellShrug,
            [MuscleGroupsNameConstants.Traps, MuscleGroupsNameConstants.Forearms]
        ),
        (ExerciseNameConstants.DumbbellSideBend, [MuscleGroupsNameConstants.Core]),
        (
            ExerciseNameConstants.DumbbellSquat,
            [
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Calves,
            ]
        ),
        (
            ExerciseNameConstants.DumbbellStandingTricepsExtension,
            [MuscleGroupsNameConstants.Triceps]
        ),
        (
            ExerciseNameConstants.DumbbellWalkingLunge,
            [MuscleGroupsNameConstants.Quads, MuscleGroupsNameConstants.Glutes]
        ),
        (ExerciseNameConstants.DumbbellWristCurl, [MuscleGroupsNameConstants.Forearms]),
        (ExerciseNameConstants.DumbbellWristExtension, [MuscleGroupsNameConstants.Forearms]),
        (ExerciseNameConstants.EccentricHeelDrop, [MuscleGroupsNameConstants.Calves]),
        (
            ExerciseNameConstants.FacePull,
            [MuscleGroupsNameConstants.Shoulders, MuscleGroupsNameConstants.Traps]
        ),
        (
            ExerciseNameConstants.FarmersWalk,
            [
                MuscleGroupsNameConstants.Forearms,
                MuscleGroupsNameConstants.Core,
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Calves,
                MuscleGroupsNameConstants.Shoulders,
            ]
        ),
        (
            ExerciseNameConstants.FatBarDeadlift,
            [
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Forearms,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Hamstrings,
                MuscleGroupsNameConstants.Traps,
            ]
        ),
        (
            ExerciseNameConstants.FeetUpBenchPress,
            [
                MuscleGroupsNameConstants.Chest,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Triceps,
            ]
        ),
        (ExerciseNameConstants.FireHydrants, [MuscleGroupsNameConstants.Glutes]),
        (ExerciseNameConstants.FloorBackExtension, [MuscleGroupsNameConstants.Back]),
        (
            ExerciseNameConstants.FloorPress,
            [
                MuscleGroupsNameConstants.Chest,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Triceps,
            ]
        ),
        (ExerciseNameConstants.ForearmExtensorExercises, [MuscleGroupsNameConstants.Forearms]),
        (
            ExerciseNameConstants.FrogPumps,
            [MuscleGroupsNameConstants.Glutes, MuscleGroupsNameConstants.Hamstrings]
        ),
        (ExerciseNameConstants.FrontHold, [MuscleGroupsNameConstants.Shoulders]),
        (
            ExerciseNameConstants.FrontSquat,
            [
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Calves,
            ]
        ),
        (
            ExerciseNameConstants.GluteBridge,
            [MuscleGroupsNameConstants.Glutes, MuscleGroupsNameConstants.Quads]
        ),
        (
            ExerciseNameConstants.GluteHamRaise,
            [
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Back,
            ]
        ),
        (
            ExerciseNameConstants.GobletSquat,
            [
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Calves,
            ]
        ),
        (
            ExerciseNameConstants.GoodMorning,
            [
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Hamstrings,
                MuscleGroupsNameConstants.Adductors,
            ]
        ),
        (
            ExerciseNameConstants.GorillaRow,
            [
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Biceps,
                MuscleGroupsNameConstants.Forearms,
                MuscleGroupsNameConstants.Shoulders,
            ]
        ),
        (ExerciseNameConstants.Gripper, [MuscleGroupsNameConstants.Forearms]),
        (
            ExerciseNameConstants.GroundToOverhead,
            [
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Calves,
                MuscleGroupsNameConstants.Forearms,
                MuscleGroupsNameConstants.Hamstrings,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Triceps,
            ]
        ),
        (
            ExerciseNameConstants.HackSquatMachine,
            [
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Adductors,
            ]
        ),
        (
            ExerciseNameConstants.HalfAirSquat,
            [
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Calves,
            ]
        ),
        (
            ExerciseNameConstants.HammerCurl,
            [MuscleGroupsNameConstants.Biceps, MuscleGroupsNameConstants.Forearms]
        ),
        (
            ExerciseNameConstants.HangClean,
            [
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Hamstrings,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Forearms,
                MuscleGroupsNameConstants.Calves,
            ]
        ),
        (
            ExerciseNameConstants.HangPowerClean,
            [
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Hamstrings,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Forearms,
                MuscleGroupsNameConstants.Calves,
            ]
        ),
        (
            ExerciseNameConstants.HangPowerSnatch,
            [
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Hamstrings,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Forearms,
                MuscleGroupsNameConstants.Calves,
            ]
        ),
        (
            ExerciseNameConstants.HangSnatch,
            [
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Hamstrings,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Forearms,
                MuscleGroupsNameConstants.Calves,
            ]
        ),
        (ExerciseNameConstants.HangingKneeRaise, [MuscleGroupsNameConstants.Core]),
        (ExerciseNameConstants.HangingLegRaise, [MuscleGroupsNameConstants.Core]),
        (ExerciseNameConstants.HangingSitUp, [MuscleGroupsNameConstants.Core]),
        (
            ExerciseNameConstants.HangingWindshieldWiper,
            [MuscleGroupsNameConstants.Core, MuscleGroupsNameConstants.Forearms]
        ),
        (ExerciseNameConstants.HeelRaise, [MuscleGroupsNameConstants.Calves]),
        (ExerciseNameConstants.HighToLowWoodChopWithCable, [MuscleGroupsNameConstants.Core]),
        (ExerciseNameConstants.HipAbductionMachine, [MuscleGroupsNameConstants.Glutes]),
        (ExerciseNameConstants.HipAdductionMachine, [MuscleGroupsNameConstants.Adductors]),
        (
            ExerciseNameConstants.HipThrust,
            [MuscleGroupsNameConstants.Glutes, MuscleGroupsNameConstants.Quads]
        ),
        (
            ExerciseNameConstants.HipThrustMachine,
            [MuscleGroupsNameConstants.Glutes, MuscleGroupsNameConstants.Quads]
        ),
        (ExerciseNameConstants.HollowBodyCrunch, [MuscleGroupsNameConstants.Core]),
        (ExerciseNameConstants.HollowHold, [MuscleGroupsNameConstants.Core]),
        (ExerciseNameConstants.HorizontalWoodChopWithCable, [MuscleGroupsNameConstants.Core]),
        (
            ExerciseNameConstants.InclineBenchPress,
            [
                MuscleGroupsNameConstants.Chest,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Triceps,
            ]
        ),
        (
            ExerciseNameConstants.InclineDumbbellCurl,
            [MuscleGroupsNameConstants.Biceps, MuscleGroupsNameConstants.Forearms]
        ),
        (
            ExerciseNameConstants.InclineDumbbellPress,
            [
                MuscleGroupsNameConstants.Chest,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Triceps,
            ]
        ),
        (
            ExerciseNameConstants.InclinePushUp,
            [
                MuscleGroupsNameConstants.Chest,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Triceps,
                MuscleGroupsNameConstants.Core,
            ]
        ),
        (
            ExerciseNameConstants.InvertedRow,
            [
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Biceps,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (
            ExerciseNameConstants.InvertedRowWithUnderhandGrip,
            [
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Biceps,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (ExerciseNameConstants.JackknifeSitUp, [MuscleGroupsNameConstants.Core]),
        (
            ExerciseNameConstants.JeffersonCurl,
            [
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Hamstrings,
                MuscleGroupsNameConstants.Traps,
            ]
        ),
        (
            ExerciseNameConstants.Jerk,
            [
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Triceps,
            ]
        ),
        (
            ExerciseNameConstants.JumpingLunge,
            [
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Adductors,
            ]
        ),
        (
            ExerciseNameConstants.JumpingMuscleUp,
            [
                MuscleGroupsNameConstants.Chest,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Triceps,
                MuscleGroupsNameConstants.Biceps,
                MuscleGroupsNameConstants.Forearms,
                MuscleGroupsNameConstants.Shoulders,
            ]
        ),
        (
            ExerciseNameConstants.JumpSquat,
            [
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Calves,
            ]
        ),
        (
            ExerciseNameConstants.KettlebellClean,
            [
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Hamstrings,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Forearms,
                MuscleGroupsNameConstants.Adductors,
            ]
        ),
        (
            ExerciseNameConstants.KettlebellCleanAndJerk,
            [
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Hamstrings,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Forearms,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Triceps,
            ]
        ),
        (
            ExerciseNameConstants.KettlebellCleanAndPress,
            [
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Hamstrings,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Forearms,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Triceps,
                MuscleGroupsNameConstants.Core,
            ]
        ),
        (
            ExerciseNameConstants.KettlebellCurl,
            [MuscleGroupsNameConstants.Biceps, MuscleGroupsNameConstants.Forearms]
        ),
        (
            ExerciseNameConstants.KettlebellFloorPress,
            [
                MuscleGroupsNameConstants.Chest,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Triceps,
            ]
        ),
        (
            ExerciseNameConstants.KettlebellFrontSquat,
            [
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Calves,
            ]
        ),
        (
            ExerciseNameConstants.KettlebellHalo,
            [
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Core,
            ]
        ),
        (ExerciseNameConstants.KettlebellPlankPullThrough, [MuscleGroupsNameConstants.Core]),
        (
            ExerciseNameConstants.KettlebellPress,
            [MuscleGroupsNameConstants.Shoulders, MuscleGroupsNameConstants.Traps]
        ),
        (
            ExerciseNameConstants.KettlebellPushPress,
            [MuscleGroupsNameConstants.Shoulders, MuscleGroupsNameConstants.Traps]
        ),
        (
            ExerciseNameConstants.KettlebellRow,
            [
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Biceps,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (
            ExerciseNameConstants.KettlebellSnatch,
            [
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Hamstrings,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (
            ExerciseNameConstants.KettlebellSwing,
            [
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Hamstrings,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (
            ExerciseNameConstants.KettlebellThrusters,
            [
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Hamstrings,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Calves,
                MuscleGroupsNameConstants.Triceps,
            ]
        ),
        (
            ExerciseNameConstants.KettlebellWindmill,
            [
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Hamstrings,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Core,
                MuscleGroupsNameConstants.Traps,
            ]
        ),
        (
            ExerciseNameConstants.KneelingInclinePushUp,
            [
                MuscleGroupsNameConstants.Chest,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Triceps,
            ]
        ),
        (ExerciseNameConstants.KneelingPlank, [MuscleGroupsNameConstants.Core]),
        (
            ExerciseNameConstants.KneelingPushUp,
            [
                MuscleGroupsNameConstants.Chest,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Triceps,
                MuscleGroupsNameConstants.Core,
            ]
        ),
        (ExerciseNameConstants.KneelingSidePlank, [MuscleGroupsNameConstants.Core]),
        (ExerciseNameConstants.KneelingAbWheelRollOut, [MuscleGroupsNameConstants.Core]),
        (
            ExerciseNameConstants.KrocRow,
            [
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Biceps,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (
            ExerciseNameConstants.LandmineHackSquat,
            [
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Adductors,
            ]
        ),
        (
            ExerciseNameConstants.LandminePress,
            [
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Triceps,
                MuscleGroupsNameConstants.Chest,
            ]
        ),
        (
            ExerciseNameConstants.LandmineRotation,
            [MuscleGroupsNameConstants.Core, MuscleGroupsNameConstants.Shoulders]
        ),
        (
            ExerciseNameConstants.LandmineSquat,
            [
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Calves,
            ]
        ),
        (
            ExerciseNameConstants.LateralBound,
            [
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Calves,
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Adductors,
            ]
        ),
        (
            ExerciseNameConstants.LatPulldownWithNeutralGrip,
            [
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Biceps,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (
            ExerciseNameConstants.LatPulldownWithPronatedGrip,
            [
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Biceps,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (
            ExerciseNameConstants.LatPulldownWithSupinatedGrip,
            [
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Biceps,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (
            ExerciseNameConstants.LegCurlOnBall,
            [MuscleGroupsNameConstants.Hamstrings, MuscleGroupsNameConstants.Glutes]
        ),
        (ExerciseNameConstants.LegExtension, [MuscleGroupsNameConstants.Quads]),
        (
            ExerciseNameConstants.LegPress,
            [
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Hamstrings,
            ]
        ),
        (
            ExerciseNameConstants.LSit,
            [
                MuscleGroupsNameConstants.Core,
                MuscleGroupsNameConstants.Chest,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Triceps,
                MuscleGroupsNameConstants.Quads,
            ]
        ),
        (ExerciseNameConstants.LyingLegCurl, [MuscleGroupsNameConstants.Hamstrings]),
        (ExerciseNameConstants.LyingLegRaise, [MuscleGroupsNameConstants.Core]),
        (ExerciseNameConstants.LyingNeckCurl, [MuscleGroupsNameConstants.Neck]),
        (ExerciseNameConstants.LyingNeckExtension, [MuscleGroupsNameConstants.Neck]),
        (ExerciseNameConstants.LyingWindshieldWiper, [MuscleGroupsNameConstants.Core]),
        (ExerciseNameConstants.LyingWindshieldWiperWithBk, [MuscleGroupsNameConstants.Core]),
        (
            ExerciseNameConstants.MachineBicepCurl,
            [MuscleGroupsNameConstants.Biceps, MuscleGroupsNameConstants.Forearms]
        ),
        (ExerciseNameConstants.MachineCrunch, [MuscleGroupsNameConstants.Core]),
        (
            ExerciseNameConstants.MachineChestFly,
            [MuscleGroupsNameConstants.Chest, MuscleGroupsNameConstants.Shoulders]
        ),
        (
            ExerciseNameConstants.MachineChestPress,
            [
                MuscleGroupsNameConstants.Chest,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Triceps,
            ]
        ),
        (
            ExerciseNameConstants.MachineGluteKickbacks,
            [MuscleGroupsNameConstants.Glutes, MuscleGroupsNameConstants.Hamstrings]
        ),
        (
            ExerciseNameConstants.MachineLatPulldown,
            [
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Biceps,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (ExerciseNameConstants.MachineLateralRaise, [MuscleGroupsNameConstants.Shoulders]),
        (
            ExerciseNameConstants.MachineShoulderPress,
            [MuscleGroupsNameConstants.Shoulders, MuscleGroupsNameConstants.Triceps]
        ),
        (
            ExerciseNameConstants.MonkeyRow,
            [
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Biceps,
            ]
        ),
        (ExerciseNameConstants.MountainClimbers, [MuscleGroupsNameConstants.Core]),
        (
            ExerciseNameConstants.MuscleUpBar,
            [
                MuscleGroupsNameConstants.Chest,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Biceps,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (
            ExerciseNameConstants.MuscleUpRings,
            [
                MuscleGroupsNameConstants.Chest,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Triceps,
                MuscleGroupsNameConstants.Biceps,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (
            ExerciseNameConstants.NeutralCloseGripLatPulldown,
            [
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Biceps,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (ExerciseNameConstants.NordicHamstringEccentric, [MuscleGroupsNameConstants.Hamstrings]),
        (ExerciseNameConstants.ObliqueCrunch, [MuscleGroupsNameConstants.Core]),
        (ExerciseNameConstants.ObliqueSitUp, [MuscleGroupsNameConstants.Core]),
        (ExerciseNameConstants.OneHandedBarHang, [MuscleGroupsNameConstants.Forearms]),
        (
            ExerciseNameConstants.OneHandedCableRow,
            [
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Biceps,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (
            ExerciseNameConstants.OneHandedKettlebellSwing,
            [
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Hamstrings,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (
            ExerciseNameConstants.OneHandedLatPulldown,
            [
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Biceps,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (
            ExerciseNameConstants.OneArmLandminePress,
            [
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Triceps,
                MuscleGroupsNameConstants.Chest,
            ]
        ),
        (
            ExerciseNameConstants.OneLeggedGluteBridge,
            [MuscleGroupsNameConstants.Glutes, MuscleGroupsNameConstants.Quads]
        ),
        (
            ExerciseNameConstants.OneLeggedHipThrust,
            [MuscleGroupsNameConstants.Glutes, MuscleGroupsNameConstants.Quads]
        ),
        (ExerciseNameConstants.OneLeggedLegExtension, [MuscleGroupsNameConstants.Quads]),
        (ExerciseNameConstants.OneLeggedLyingLegCurl, [MuscleGroupsNameConstants.Hamstrings]),
        (ExerciseNameConstants.OneLeggedSeatedLegCurl, [MuscleGroupsNameConstants.Hamstrings]),
        (ExerciseNameConstants.OverheadCableTricepsExtension, [MuscleGroupsNameConstants.Triceps]),
        (
            ExerciseNameConstants.OverheadPress,
            [MuscleGroupsNameConstants.Shoulders, MuscleGroupsNameConstants.Triceps]
        ),
        (
            ExerciseNameConstants.PauseDeadlift,
            [
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Hamstrings,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (
            ExerciseNameConstants.PauseSquat,
            [
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Calves,
            ]
        ),
        (
            ExerciseNameConstants.PecDeck,
            [MuscleGroupsNameConstants.Chest, MuscleGroupsNameConstants.Shoulders]
        ),
        (
            ExerciseNameConstants.PendlayRow,
            [
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (
            ExerciseNameConstants.PinBenchPress,
            [
                MuscleGroupsNameConstants.Chest,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Triceps,
            ]
        ),
        (
            ExerciseNameConstants.PinSquat,
            [
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Calves,
            ]
        ),
        (
            ExerciseNameConstants.PistolSquat,
            [
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Hamstrings,
            ]
        ),
        (ExerciseNameConstants.PlateFrontRaise, [MuscleGroupsNameConstants.Shoulders]),
        (ExerciseNameConstants.PlatePinch, [MuscleGroupsNameConstants.Forearms]),
        (ExerciseNameConstants.PlateWristCurl, [MuscleGroupsNameConstants.Forearms]),
        (ExerciseNameConstants.Plank, [MuscleGroupsNameConstants.Core]),
        (
            ExerciseNameConstants.PlankToPushUp,
            [
                MuscleGroupsNameConstants.Chest,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Triceps,
                MuscleGroupsNameConstants.Core,
            ]
        ),
        (ExerciseNameConstants.PlankWithLegLifts, [MuscleGroupsNameConstants.Core]),
        (ExerciseNameConstants.PlankWithShoulderTaps, [MuscleGroupsNameConstants.Core]),
        (ExerciseNameConstants.PoliquinRaise, [MuscleGroupsNameConstants.Shoulders]),
        (ExerciseNameConstants.PoliquinStepUp, [MuscleGroupsNameConstants.Quads]),
        (
            ExerciseNameConstants.PowerClean,
            [
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Hamstrings,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (
            ExerciseNameConstants.PowerJerk,
            [
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Triceps,
            ]
        ),
        (
            ExerciseNameConstants.PowerSnatch,
            [
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Hamstrings,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (
            ExerciseNameConstants.PrisonerGetUp,
            [
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Core,
                MuscleGroupsNameConstants.Adductors,
            ]
        ),
        (
            ExerciseNameConstants.PullUp,
            [
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Biceps,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (
            ExerciseNameConstants.PullUpWithNeutralGrip,
            [
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Biceps,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (
            ExerciseNameConstants.PushPress,
            [
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Triceps,
            ]
        ),
        (
            ExerciseNameConstants.PushUp,
            [
                MuscleGroupsNameConstants.Chest,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Triceps,
                MuscleGroupsNameConstants.Core,
            ]
        ),
        (
            ExerciseNameConstants.PushUpAgainstWall,
            [
                MuscleGroupsNameConstants.Chest,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Triceps,
                MuscleGroupsNameConstants.Core,
            ]
        ),
        (
            ExerciseNameConstants.PushUpsWithFeetInRings,
            [
                MuscleGroupsNameConstants.Chest,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Triceps,
                MuscleGroupsNameConstants.Core,
            ]
        ),
        (
            ExerciseNameConstants.RackPull,
            [
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Hamstrings,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (
            ExerciseNameConstants.RenegadeRow,
            [
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Biceps,
                MuscleGroupsNameConstants.Forearms,
                MuscleGroupsNameConstants.Core,
            ]
        ),
        (
            ExerciseNameConstants.ReverseBarbellLunge,
            [
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Glutes,
            ]
        ),
        (
            ExerciseNameConstants.ReverseBodyWeightLunge,
            [
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Adductors,
            ]
        ),
        (
            ExerciseNameConstants.ReverseCableFlyes,
            [MuscleGroupsNameConstants.Shoulders, MuscleGroupsNameConstants.Traps]
        ),
        (
            ExerciseNameConstants.ReverseDumbbellFlyes,
            [MuscleGroupsNameConstants.Shoulders, MuscleGroupsNameConstants.Traps]
        ),
        (
            ExerciseNameConstants.ReverseDumbbellLunge,
            [
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (
            ExerciseNameConstants.ReverseHyperextension,
            [
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Hamstrings,
                MuscleGroupsNameConstants.Back,
            ]
        ),
        (
            ExerciseNameConstants.ReverseMachineFly,
            [MuscleGroupsNameConstants.Shoulders, MuscleGroupsNameConstants.Traps]
        ),
        (ExerciseNameConstants.ReverseNordic, [MuscleGroupsNameConstants.Quads]),
        (
            ExerciseNameConstants.RingDip,
            [
                MuscleGroupsNameConstants.Chest,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Triceps,
            ]
        ),
        (
            ExerciseNameConstants.RingPullUp,
            [
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Biceps,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (
            ExerciseNameConstants.RingRow,
            [
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Biceps,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (
            ExerciseNameConstants.RomanianDeadlift,
            [
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Hamstrings,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (
            ExerciseNameConstants.RomanianDeadliftGlute,
            [
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Hamstrings,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (
            ExerciseNameConstants.SafetyBarSquat,
            [
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Calves,
            ]
        ),
        (
            ExerciseNameConstants.ScapPullUp,
            [MuscleGroupsNameConstants.Shoulders, MuscleGroupsNameConstants.Forearms]
        ),
        (
            ExerciseNameConstants.SeatedBarbellOverheadPress,
            [MuscleGroupsNameConstants.Shoulders, MuscleGroupsNameConstants.Triceps]
        ),
        (
            ExerciseNameConstants.SeatedCableChestFly,
            [MuscleGroupsNameConstants.Chest, MuscleGroupsNameConstants.Shoulders]
        ),
        (ExerciseNameConstants.SeatedCalfRaise, [MuscleGroupsNameConstants.Calves]),
        (
            ExerciseNameConstants.SeatedDumbbellShoulderPress,
            [MuscleGroupsNameConstants.Shoulders, MuscleGroupsNameConstants.Triceps]
        ),
        (
            ExerciseNameConstants.SeatedKettlebellPress,
            [MuscleGroupsNameConstants.Shoulders, MuscleGroupsNameConstants.Triceps]
        ),
        (ExerciseNameConstants.SeatedLegCurl, [MuscleGroupsNameConstants.Hamstrings]),
        (
            ExerciseNameConstants.SeatedMachineRow,
            [
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Biceps,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (
            ExerciseNameConstants.SeatedSmithMachineShoulderPress,
            [MuscleGroupsNameConstants.Shoulders, MuscleGroupsNameConstants.Triceps]
        ),
        (
            ExerciseNameConstants.SealRow,
            [
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Biceps,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (
            ExerciseNameConstants.ShallowBodyWeightLunge,
            [
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Hamstrings,
            ]
        ),
        (
            ExerciseNameConstants.SideLungesBodyweight,
            [
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Adductors,
            ]
        ),
        (ExerciseNameConstants.SidePlank, [MuscleGroupsNameConstants.Core]),
        (
            ExerciseNameConstants.SingleLegDeadliftWithKettlebell,
            [
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Hamstrings,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Abductors,
                MuscleGroupsNameConstants.Forearms,
                MuscleGroupsNameConstants.Traps,
            ]
        ),
        (
            ExerciseNameConstants.SingleLegRomanianDeadlift,
            [
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Hamstrings,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (ExerciseNameConstants.SitUp, [MuscleGroupsNameConstants.Core]),
        (
            ExerciseNameConstants.SmithMachineBenchPress,
            [
                MuscleGroupsNameConstants.Chest,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Triceps,
            ]
        ),
        (
            ExerciseNameConstants.SmithMachineBulgarianSplitSquat,
            [
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Adductors,
            ]
        ),
        (
            ExerciseNameConstants.SmithMachineDeadlift,
            [
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Forearms,
                MuscleGroupsNameConstants.Hamstrings,
            ]
        ),
        (
            ExerciseNameConstants.SmithMachineFrontSquat,
            [
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Calves,
            ]
        ),
        (
            ExerciseNameConstants.SmithMachineHipThrust,
            [MuscleGroupsNameConstants.Glutes, MuscleGroupsNameConstants.Quads]
        ),
        (
            ExerciseNameConstants.SmithMachineInclineBenchPress,
            [
                MuscleGroupsNameConstants.Chest,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Triceps,
            ]
        ),
        (
            ExerciseNameConstants.SmithMachineLandminePress,
            [
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Triceps,
                MuscleGroupsNameConstants.Chest,
            ]
        ),
        (
            ExerciseNameConstants.SmithMachineOneHandedRow,
            [
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Biceps,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (
            ExerciseNameConstants.SmithMachineReverseGripBp,
            [
                MuscleGroupsNameConstants.Chest,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Triceps,
            ]
        ),
        (
            ExerciseNameConstants.SmithMachineRomanianDeadlift,
            [
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Adductors,
            ]
        ),
        (
            ExerciseNameConstants.SmithMachineSquat,
            [
                MuscleGroupsNameConstants.Hamstrings,
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Forearms,
                MuscleGroupsNameConstants.Adductors,
            ]
        ),
        (
            ExerciseNameConstants.Snatch,
            [
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Hamstrings,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (
            ExerciseNameConstants.SnatchGripDeadlift,
            [
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Forearms,
                MuscleGroupsNameConstants.Hamstrings,
            ]
        ),
        (
            ExerciseNameConstants.SpiderCurl,
            [MuscleGroupsNameConstants.Biceps, MuscleGroupsNameConstants.Forearms]
        ),
        (
            ExerciseNameConstants.SplitJerk,
            [
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Triceps,
            ]
        ),
        (
            ExerciseNameConstants.Squat,
            [
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Calves,
            ]
        ),
        (
            ExerciseNameConstants.SquatJerk,
            [
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Triceps,
                MuscleGroupsNameConstants.Calves,
            ]
        ),
        (
            ExerciseNameConstants.StandingCableChestFly,
            [MuscleGroupsNameConstants.Chest, MuscleGroupsNameConstants.Shoulders]
        ),
        (ExerciseNameConstants.StandingCableLegExtension, [MuscleGroupsNameConstants.Quads]),
        (ExerciseNameConstants.StandingCalfRaise, [MuscleGroupsNameConstants.Calves]),
        (
            ExerciseNameConstants.StandingGluteKickbackInMachine,
            [MuscleGroupsNameConstants.Glutes, MuscleGroupsNameConstants.Hamstrings]
        ),
        (
            ExerciseNameConstants.StandingGlutePushDown,
            [MuscleGroupsNameConstants.Glutes, MuscleGroupsNameConstants.Hamstrings]
        ),
        (
            ExerciseNameConstants.StepUp,
            [
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Hamstrings,
            ]
        ),
        (
            ExerciseNameConstants.StepUpGlute,
            [
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Hamstrings,
            ]
        ),
        (
            ExerciseNameConstants.StiffLeggedDeadlift,
            [
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Forearms,
                MuscleGroupsNameConstants.Hamstrings,
            ]
        ),
        (
            ExerciseNameConstants.StraightArmLatPulldown,
            [MuscleGroupsNameConstants.Back, MuscleGroupsNameConstants.Shoulders]
        ),
        (
            ExerciseNameConstants.SumoDeadlift,
            [
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Forearms,
                MuscleGroupsNameConstants.Hamstrings,
            ]
        ),
        (
            ExerciseNameConstants.SumoSquat,
            [
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Calves,
            ]
        ),
        (
            ExerciseNameConstants.SupermanRaise,
            [
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Hamstrings,
            ]
        ),
        (
            ExerciseNameConstants.TatePress,
            [
                MuscleGroupsNameConstants.Triceps,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Chest,
            ]
        ),
        (
            ExerciseNameConstants.TbarRow,
            [
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Biceps,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (
            ExerciseNameConstants.TowelPullUp,
            [
                MuscleGroupsNameConstants.Forearms,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Biceps,
                MuscleGroupsNameConstants.Shoulders,
            ]
        ),
        (
            ExerciseNameConstants.TowelRow,
            [
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Biceps,
            ]
        ),
        (
            ExerciseNameConstants.TrapBarDeadliftWithHighHandles,
            [
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (
            ExerciseNameConstants.TrapBarDeadliftWithLowHandles,
            [
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Traps,
                MuscleGroupsNameConstants.Forearms,
            ]
        ),
        (
            ExerciseNameConstants.TricepBodyweightExtension,
            [MuscleGroupsNameConstants.Triceps, MuscleGroupsNameConstants.Core]
        ),
        (ExerciseNameConstants.TricepPushdownWithBar, [MuscleGroupsNameConstants.Triceps]),
        (ExerciseNameConstants.TricepPushdownWithRope, [MuscleGroupsNameConstants.Triceps]),
        (ExerciseNameConstants.WeightedPlank, [MuscleGroupsNameConstants.Core]),
        (ExerciseNameConstants.WristRoller, [MuscleGroupsNameConstants.Forearms]),
        (
            ExerciseNameConstants.ZercherSquat,
            [
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Calves,
            ]
        ),
        (
            ExerciseNameConstants.ZombieSquat,
            [
                MuscleGroupsNameConstants.Quads,
                MuscleGroupsNameConstants.Glutes,
                MuscleGroupsNameConstants.Adductors,
                MuscleGroupsNameConstants.Back,
                MuscleGroupsNameConstants.Calves,
            ]
        ),
        (
            ExerciseNameConstants.ZottmanCurl,
            [MuscleGroupsNameConstants.Biceps, MuscleGroupsNameConstants.Forearms]
        ),
        (
            ExerciseNameConstants.ZPress,
            [
                MuscleGroupsNameConstants.Shoulders,
                MuscleGroupsNameConstants.Triceps,
                MuscleGroupsNameConstants.Chest,
                MuscleGroupsNameConstants.Traps,
            ]
        ),
    ];

    public async Task SeedAsync(IServiceProvider provider, CancellationToken cancellationToken)
    {
        using var scope = provider.CreateScope();
        var database = scope.ServiceProvider.GetRequiredService<LiftLogDatabase>();
        var logger = scope.ServiceProvider.GetService<ILogger<ExerciseSeeder>>();

        var existingExerciseNames = (
            await database.Exercises.Select(x => x.Name).ToListAsync(cancellationToken)
        ).ToHashSet(StringComparer.OrdinalIgnoreCase);

        var muscleGroups = await database
            .MuscleGroups.Select(mg => new { mg.Id, mg.Name })
            .ToListAsync(cancellationToken);

        var muscleGroupLookup = muscleGroups.ToDictionary(
            x => x.Name,
            x => x.Id,
            StringComparer.OrdinalIgnoreCase
        );

        var add = new List<Exercise>();

        foreach (var (exerciseName, mgNames) in Exercises)
        {
            if (existingExerciseNames.Contains(exerciseName))
                continue;

            var foundIds = new List<Guid>();
            foreach (var mgName in mgNames)
            {
                if (muscleGroupLookup.TryGetValue(mgName, out var guid))
                    foundIds.Add(guid);
                else
                    logger?.LogWarning(
                        "Muscle group '{MuscleGroupName}' referenced by exercise '{ExerciseName}' was not found in DB. Skipping that muscle group.",
                        mgName,
                        exerciseName
                    );
            }

            if (foundIds.Count == 0)
            {
                logger?.LogWarning(
                    "No muscle groups found for exercise '{ExerciseName}', skipping creation.",
                    exerciseName
                );
                continue;
            }

            add.Add(Exercise.Create(foundIds, exerciseName));
        }

        if (add.Count > 0)
        {
            database.Exercises.AddRange(add);
            await database.SaveChangesAsync(cancellationToken);
            logger?.LogInformation("Seeded {Count} new exercises.", add.Count);
        }
        else
        {
            logger?.LogDebug("No new exercise to seed.");
        }
    }
}
